### ISSUE TITLE
Add Cake Addin to Website

### ISSUE THREAD

**Issue by gep13** [Kemyke/Cake.Tfs.Build.Variables#1]
Great work on getting this addin created!

This is just a suggestion, but think it would be a really good idea, to help with visibility of this addin.

i.e. get your addin listed here:

http://cakebuild.net/addins

Have a look at this PR:

cake-build/website#290

This assumes that you have added XML Documentation to your addin, as described here:

http://cakebuild.net/docs/contributing/documentation

Let me know if you have any questions. Thanks!

**Comment by Kemyke** [comment]
Hi @gep13 

i uploaded the XML docs and tests for this project. Can you please check them and verify it. 
If you found it ok, i will do the PR for the website.

Thanks!

**Comment by gep13** [comment]
Your NuGet package doesn't seem to contain the XML Documentation file that would be needed to show the documentation on the website.

Have a look at the content of this package:

https://www.nuget.org/packages/Cake.Gitter/

For an example of what is expected.

**Comment by Kemyke** [comment]
Oh wait, i haven't created new package yet. I've just added the comments in code.

**Comment by Kemyke** [comment]
Now i uploaded the version 0.0.6. It is not yet indexed. Please check this version.

**Comment by gep13** [comment]
That looks better 😄 

If you make the change to the website, and build/run the website locally, you should be able to see if the XML comments are pulled through correctly onto the site.

**Comment by gep13** [comment]
@Kemyke perfect, I will try to get that, and your other PR, merged tomorrow.  Thanks for doing this! 😄

**Comment by Kemyke** [comment]
No worries! I am happy to help the community. I hope these packages will be useful for others.

**Comment by gep13** [comment]
I am sure that they will be 👍

**Comment by gep13** [comment]
@Kemyke thank you for doing this!
